version: "2.4"
services:
  app:
    build:
      context: .
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__connectionDetails=Host=db;Port=5432;Database=postgres;Username=postgres;Password=
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:10.1-alpine
    ports:
      - 5432:5432
  tests:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - ConnectionStrings__connectionDetails=Host=db;Port=5432;Database=postgres;Username=postgres;Password=
    depends_on:
      - db
    command: >
      sh -c "dotnet test --settings runsetting.xml"
